package net.intellizone.coupon.msg.sms.send;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SendSmsService service = new SendSmsService();
 * SendSms portType = service.getSendSms();
 * portType.sendSms(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "SendSmsService", targetNamespace = "http://www.chinatelecom.com.cn/wsdl/ctcc/sms/send/v2_1/service", wsdlLocation = "file:/D:/platform/platform/coupon/wsdl/ctcc_sms_send_service_2_1.wsdl")
public class SendSmsService extends Service {

	private final static URL SENDSMSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(net.intellizone.coupon.msg.sms.send.SendSmsService.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = net.intellizone.coupon.msg.sms.send.SendSmsService.class.getResource(".");
			url = new URL(baseUrl, "file:/D:/platform/platform/coupon/wsdl/ctcc_sms_send_service_2_1.wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'file:/D:/platform/platform/coupon/wsdl/ctcc_sms_send_service_2_1.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SENDSMSSERVICE_WSDL_LOCATION = url;
	}

	public SendSmsService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SendSmsService() {
		super(SENDSMSSERVICE_WSDL_LOCATION, new QName("http://www.chinatelecom.com.cn/wsdl/ctcc/sms/send/v2_1/service",
				"SendSmsService"));
	}

	/**
	 * 
	 * @return returns SendSms
	 */
	@WebEndpoint(name = "SendSms")
	public SendSms getSendSms() {
		return super.getPort(new QName("http://www.chinatelecom.com.cn/wsdl/ctcc/sms/send/v2_1/service", "SendSms"),
				SendSms.class);
	}

}
