package net.intellizone.coupon.msg.mms.receive;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.intellizone.coupon.msg.mms.common.DeliveryInformation;
import net.intellizone.coupon.msg.mms.common.MessageReference;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MessageNotification", targetNamespace = "http://www.chinatelecom.com.cn/wsdl/ctcc/multimedia_messaging/notification/v2_2/interface")
public interface MessageNotification {

	/**
	 * 
	 * @param message
	 * @param registrationIdentifier
	 */
	@WebMethod
	@RequestWrapper(localName = "notifyMessageReception", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/notification/v2_2/local", className = "net.intellizone.coupon.msg.mms.receive.NotifyMessageReception")
	@ResponseWrapper(localName = "notifyMessageReceptionResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/notification/v2_2/local", className = "net.intellizone.coupon.msg.mms.receive.NotifyMessageReceptionResponse")
	public void notifyMessageReception(
			@WebParam(name = "registrationIdentifier", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/notification/v2_2/local")
			String registrationIdentifier,
			@WebParam(name = "message", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/notification/v2_2/local")
			MessageReference message);

	/**
	 * 
	 * @param correlator
	 * @param deliveryStatus
	 */
	@WebMethod
	@RequestWrapper(localName = "notifyMessageDeliveryReceipt", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/notification/v2_2/local", className = "net.intellizone.coupon.msg.mms.receive.NotifyMessageDeliveryReceipt")
	@ResponseWrapper(localName = "notifyMessageDeliveryReceiptResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/notification/v2_2/local", className = "net.intellizone.coupon.msg.mms.receive.NotifyMessageDeliveryReceiptResponse")
	public void notifyMessageDeliveryReceipt(
			@WebParam(name = "correlator", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/notification/v2_2/local")
			String correlator,
			@WebParam(name = "deliveryStatus", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/notification/v2_2/local")
			DeliveryInformation deliveryStatus);

}
