package net.intellizone.coupon.msg.mms.send;

import javax.xml.ws.WebFault;

import net.intellizone.coupon.msg.common.PolicyException;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "PolicyException", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/common/v2_1")
public class PolicyException_Exception extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private PolicyException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public PolicyException_Exception(String message, PolicyException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public PolicyException_Exception(String message, PolicyException faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         net.intellizone.coupon.msg.mms.send.PolicyException
	 */
	public PolicyException getFaultInfo() {
		return faultInfo;
	}

}
