package net.intellizone.coupon.msg.mms.send;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SendMessageService service = new SendMessageService();
 * SendMessage portType = service.getSendMessage();
 * portType.sendMessage(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "SendMessageService", targetNamespace = "http://www.chinatelecom.com.cn/wsdl/ctcc/multimedia_messaging/send/v2_2/service", wsdlLocation = "file:/D:/platform/platform/coupon/wsdl/ctcc_mm_send_service_2_2.wsdl")
public class SendMessageService extends Service {

	private final static URL SENDMESSAGESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(net.intellizone.coupon.msg.mms.send.SendMessageService.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = net.intellizone.coupon.msg.mms.send.SendMessageService.class.getResource(".");
			url = new URL(baseUrl, "file:/D:/platform/platform/coupon/wsdl/ctcc_mm_send_service_2_2.wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'file:/D:/platform/platform/coupon/wsdl/ctcc_mm_send_service_2_2.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SENDMESSAGESERVICE_WSDL_LOCATION = url;
	}

	public SendMessageService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SendMessageService() {
		super(SENDMESSAGESERVICE_WSDL_LOCATION,
				new QName("http://www.chinatelecom.com.cn/wsdl/ctcc/multimedia_messaging/send/v2_2/service",
						"SendMessageService"));
	}

	/**
	 * 
	 * @return returns SendMessage
	 */
	@WebEndpoint(name = "SendMessage")
	public SendMessage getSendMessage() {
		return super.getPort(new QName(
				"http://www.chinatelecom.com.cn/wsdl/ctcc/multimedia_messaging/send/v2_2/service", "SendMessage"),
				SendMessage.class);
	}

}
