package net.intellizone.coupon.msg.mms.send;

import javax.xml.ws.WebFault;

import net.intellizone.coupon.msg.common.ServiceException;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "ServiceException", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/common/v2_1")
public class ServiceException_Exception extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private ServiceException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public ServiceException_Exception(String message, ServiceException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public ServiceException_Exception(String message, ServiceException faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         net.intellizone.coupon.msg.mms.send.ServiceException
	 */
	public ServiceException getFaultInfo() {
		return faultInfo;
	}

}
