package net.intellizone.coupon.msg.mms.send;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.intellizone.coupon.msg.common.ChargingInformation;
import net.intellizone.coupon.msg.common.SimpleReference;
import net.intellizone.coupon.msg.mms.common.DeliveryInformation;
import net.intellizone.coupon.msg.mms.common.MessagePriority;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SendMessage", targetNamespace = "http://www.chinatelecom.com.cn/wsdl/ctcc/multimedia_messaging/send/v2_2/interface")
public interface SendMessage {

	/**
	 * 
	 * @param senderAddress
	 * @param receiptRequest
	 * @param priority
	 * @param subject
	 * @param charging
	 * @param addresses
	 * @return returns java.lang.String
	 * @throws PolicyException_Exception
	 * @throws ServiceException_Exception
	 */
	@WebMethod
	@WebResult(name = "result", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local")
	@RequestWrapper(localName = "sendMessage", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local", className = "net.intellizone.coupon.msg.mms.send.SendMessage_Type")
	@ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local", className = "net.intellizone.coupon.msg.mms.send.SendMessageResponse")
	public String sendMessage(
			@WebParam(name = "addresses", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local")
			List<String> addresses,
			@WebParam(name = "senderAddress", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local")
			String senderAddress,
			@WebParam(name = "subject", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local")
			String subject,
			@WebParam(name = "priority", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local")
			MessagePriority priority,
			@WebParam(name = "charging", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local")
			ChargingInformation charging,
			@WebParam(name = "receiptRequest", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local")
			SimpleReference receiptRequest) throws PolicyException_Exception, ServiceException_Exception;

	/**
	 * 
	 * @param requestIdentifier
	 * @return returns java.util.List<net.intellizone.coupon.msg.mms.send.DeliveryInformation>
	 * @throws PolicyException_Exception
	 * @throws ServiceException_Exception
	 */
	@WebMethod
	@WebResult(name = "result", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local")
	@RequestWrapper(localName = "getMessageDeliveryStatus", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local", className = "net.intellizone.coupon.msg.mms.send.GetMessageDeliveryStatus")
	@ResponseWrapper(localName = "getMessageDeliveryStatusResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local", className = "net.intellizone.coupon.msg.mms.send.GetMessageDeliveryStatusResponse")
	public List<DeliveryInformation> getMessageDeliveryStatus(
			@WebParam(name = "requestIdentifier", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/multimedia_messaging/send/v2_2/local")
			String requestIdentifier) throws PolicyException_Exception, ServiceException_Exception;

}
