package net.intellizone.coupon.user.services.wingspay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ProvinceWsInterDelegate", targetNamespace = "http://wsi.huateng.com/")
public interface ProvinceWsInterDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "doBusiness", targetNamespace = "http://wsi.huateng.com/", className = "net.intellizone.coupon.user.services.wingspay.DoBusiness")
	@ResponseWrapper(localName = "doBusinessResponse", targetNamespace = "http://wsi.huateng.com/", className = "net.intellizone.coupon.user.services.wingspay.DoBusinessResponse")
	public String doBusiness(@WebParam(name = "arg0", targetNamespace = "")
	String arg0);

}
