package net.intellizone.coupon.msg.sms.send;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import net.intellizone.coupon.msg.common.ChargingInformation;
import net.intellizone.coupon.msg.common.SimpleReference;
import net.intellizone.coupon.msg.sms.common.DeliveryInformation;
import net.intellizone.coupon.msg.sms.common.SmsFormat;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SendSms", targetNamespace = "http://www.chinatelecom.com.cn/wsdl/ctcc/sms/send/v2_1/interface")
public interface SendSms {

	/**
	 * 
	 * @param message
	 * @param senderName
	 * @param receiptRequest
	 * @param charging
	 * @param addresses
	 * @return returns java.lang.String
	 * @throws ServiceException_Exception
	 * @throws PolicyException_Exception
	 */
	@WebMethod
	@WebResult(name = "result", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
	@RequestWrapper(localName = "sendSms", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "net.intellizone.coupon.msg.sms.send.SendSms_Type")
	@ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "net.intellizone.coupon.msg.sms.send.SendSmsResponse")
	public String sendSms(
			@WebParam(name = "addresses", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			List<String> addresses,
			@WebParam(name = "senderName", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			String senderName,
			@WebParam(name = "charging", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			ChargingInformation charging,
			@WebParam(name = "message", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			String message,
			@WebParam(name = "receiptRequest", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			SimpleReference receiptRequest) throws PolicyException_Exception, ServiceException_Exception;

	/**
	 * 
	 * @param senderName
	 * @param receiptRequest
	 * @param smsFormat
	 * @param charging
	 * @param image
	 * @param addresses
	 * @return returns java.lang.String
	 * @throws ServiceException_Exception
	 * @throws PolicyException_Exception
	 */
	@WebMethod
	@WebResult(name = "result", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
	@RequestWrapper(localName = "sendSmsLogo", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "net.intellizone.coupon.msg.sms.send.SendSmsLogo")
	@ResponseWrapper(localName = "sendSmsLogoResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "net.intellizone.coupon.msg.sms.send.SendSmsLogoResponse")
	public String sendSmsLogo(
			@WebParam(name = "addresses", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			List<String> addresses,
			@WebParam(name = "senderName", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			String senderName,
			@WebParam(name = "charging", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			ChargingInformation charging,
			@WebParam(name = "image", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			byte[] image,
			@WebParam(name = "smsFormat", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			SmsFormat smsFormat,
			@WebParam(name = "receiptRequest", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			SimpleReference receiptRequest) throws PolicyException_Exception, ServiceException_Exception;

	/**
	 * 
	 * @param senderName
	 * @param receiptRequest
	 * @param smsFormat
	 * @param charging
	 * @param ringtone
	 * @param addresses
	 * @return returns java.lang.String
	 * @throws ServiceException_Exception
	 * @throws PolicyException_Exception
	 */
	@WebMethod
	@WebResult(name = "result", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
	@RequestWrapper(localName = "sendSmsRingtone", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "net.intellizone.coupon.msg.sms.send.SendSmsRingtone")
	@ResponseWrapper(localName = "sendSmsRingtoneResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "net.intellizone.coupon.msg.sms.send.SendSmsRingtoneResponse")
	public String sendSmsRingtone(
			@WebParam(name = "addresses", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			List<String> addresses,
			@WebParam(name = "senderName", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			String senderName,
			@WebParam(name = "charging", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			ChargingInformation charging,
			@WebParam(name = "ringtone", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			String ringtone,
			@WebParam(name = "smsFormat", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			SmsFormat smsFormat,
			@WebParam(name = "receiptRequest", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			SimpleReference receiptRequest) throws PolicyException_Exception, ServiceException_Exception;

	/**
	 * 
	 * @param requestIdentifier
	 * @return returns java.util.List<net.intellizone.coupon.msg.sms.send.DeliveryInformation>
	 * @throws ServiceException_Exception
	 * @throws PolicyException_Exception
	 */
	@WebMethod
	@WebResult(name = "result", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
	@RequestWrapper(localName = "getSmsDeliveryStatus", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "net.intellizone.coupon.msg.sms.send.GetSmsDeliveryStatus")
	@ResponseWrapper(localName = "getSmsDeliveryStatusResponse", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local", className = "net.intellizone.coupon.msg.sms.send.GetSmsDeliveryStatusResponse")
	public List<DeliveryInformation> getSmsDeliveryStatus(
			@WebParam(name = "requestIdentifier", targetNamespace = "http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local")
			String requestIdentifier) throws PolicyException_Exception, ServiceException_Exception;

}
